### ISSUE TITLE
Issues with pypi release

### ISSUE THREAD

**Issue by borisaguilar** [vinyldarkscratch/pylint_web2py2#1]
Current code uses newer pylint, released code uses older pylint (2.3.1 pylint seems to work) but when I run the installed version from pypi with latest pylint (2.5.2) the following exception appears:

```
  File "/usr/local/Caskroom/miniconda/base/lib/python3.6/site-packages/pylint_web2py3/__init__.py", line 30, in <module>
    from pylint.utils import PyLintASTWalker
ImportError: cannot import name 'PyLintASTWalker'
```

**Comment by vinyldarkscratch** [comment]
Seems a bit odd that it would not be able to import the library -- the package was written for PyLint 2.4.0, and if they're making backwards-incompatible changes, that's against semantic versioning... :/

I'll do some digging around and try to get a fix out ASAP!

**Comment by queengooborg** [comment]
I have just deployed a new release, sorry about that!  I'm not sure why it was released incorrectly before: https://pypi.org/project/pylint-web2py3/0.9.1/

**Comment by borisaguilar** [comment]
It is still not installing 0.9.1 correctly from pypi, its trying to open a non-existant requirements.txt:
<pre>
% pip install pylint_web2py3==0.9.1       
Collecting pylint_web2py3
  Using cached pylint_web2py3-0.9.1.tar.gz (4.9 kB)
    ERROR: Command errored out with exit status 1:
     command: /usr/local/Caskroom/miniconda/base/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/x6/r5blmg9n0l1gy56q7_5hp5400000gn/T/pip-install-3ha2cj6g/pylint-web2py3/setup.py'"'"'; __file__='"'"'/private/var/folders/x6/r5blmg9n0l1gy56q7_5hp5400000gn/T/pip-install-3ha2cj6g/pylint-web2py3/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/x6/r5blmg9n0l1gy56q7_5hp5400000gn/T/pip-install-3ha2cj6g/pylint-web2py3/pip-egg-info
         cwd: /private/var/folders/x6/r5blmg9n0l1gy56q7_5hp5400000gn/T/pip-install-3ha2cj6g/pylint-web2py3/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/x6/r5blmg9n0l1gy56q7_5hp5400000gn/T/pip-install-3ha2cj6g/pylint-web2py3/setup.py", line 9, in <module>
        with open('requirements.txt') as f:
    FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
</pre>

**Comment by queengooborg** [comment]
Ah, crap...  Sorry, it’s been a while since I’ve done things with Python packages, as my employer has had me working in React a lot more lately.

Unfortunately I won’t be able to update this package for a while due to time constraints, however I’ll reopen this issue and let you know when I’ve got it fully functional!

**Comment by queengooborg** [comment]
Alright, sorry for the wait on this, but I've done a new release to get this functioning as expected!
